spring:
  datasource:
    username: root
    password: ?rootXyb_
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/scrm_sop?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true


logging:
  config: classpath:logback-spring.xml

hook:
  timeout: 3000
  url: http://127.0.0.1:8031/globalInfo/refresh